### ISSUE TITLE
The context menu option for copying to clipboard cannot be found in Rider 2024.2.5

### ISSUE THREAD

**Issue by uldahlalex** [mwguerra/copy-file-content#2]
The settings menu does appear, but the neither solution overview or file system overview for copying file contents to clipboard appears.

I tried in Webstorm and that one works just fine.

Exact version of Rider:  Build #RD-242.22855.90, built on September 19, 2024

Runtime version: 21.0.3+13-b509.15 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by mwguerra** [comment]
Hi, I'll have a look. Thanks for opening the issue!

**Comment by mwguerra** [comment]
You are right. Rider has a different set of action groups and menus for .Net. I'll update that and let you know here.

**Comment by mwguerra** [comment]
The menu structure for Rider and Resharper is really different. For now I'll add the Copy File Content menu under the context of "Copy Path/Reference...". I'll need to investigate new way to handle that better in the future. It should be available in 1.0.3 in 2 or 3 days. Thanks again for showing me that.

**Comment by uldahlalex** [comment]
Thanks for taking your time to investigate
